---

- name: taking iptables backup | /opt/iptables-{{ ansible_date_time.date }}.bak
  shell: "iptables-save > /opt/iptables-{{ ansible_date_time.date }}.bak"
  args:
    creates: "/opt/iptables-{{ ansible_date_time.date }}.bak"

- name: flushing all iptables rules if exists
  command: iptables -F
