---
# Variables to create service file to Zookeeper

systemd_service_filename: "zookeeper.service"
systemd_service_description: "Zookeeper"
systemd_service_after: "syslog.target network.target"
systemd_service_user: "root"
systemd_service_group: "root"
systemd_service_type: "simple"
systemd_service_execstart: "/opt/zookeeper-3.4.14/bin/zkServer.sh start-foreground"
systemd_service_execstop: "/opt/zookeeper-3.4.14/bin/zkServer.sh stop"
systemd_service_restart: "on-failure"
systemd_service_restartsec: "5s"
systemd_service_wantedby: "multi-user.target"
systemd_service_wants: ""
systemd_service_annotation: ""
systemd_service_environmentfile: ""
systemd_service_standardoutput: ""
systemd_service_standarderror: ""
systemd_service_syslogidentifier: ""
systemd_service_privatetmp: ""